<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <!--<Nullable>enable</Nullable>-->
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting> <!-- GitHub Actions -->
  </PropertyGroup>

  <PropertyGroup>
    <VersionPrefix>1.0</VersionPrefix>
    <VersionInfo>$(VersionPrefix).$([System.DateTime]::UtcNow.DayOfYear.ToString().PadLeft(3, '0')).$([System.DateTime]::UtcNow.Hour.ToString().PadLeft(2, '0'))$([System.DateTime]::UtcNow.Minute.ToString().PadLeft(2, '0'))</VersionInfo>
    <AssemblyVersion>$(VersionPrefix).0.0</AssemblyVersion>
    <FileVersion>$(VersionInfo)</FileVersion>
    <Version>$(VersionPrefix).0.0</Version>
  </PropertyGroup>

  <Choose>
    <When Condition="Exists('..\..\ObservatoryCore\ObservatoryFramework\ObservatoryFramework.csproj')">
    <ItemGroup>
      <ProjectReference Include="..\..\ObservatoryCore\ObservatoryFramework\ObservatoryFramework.csproj" />
    </ItemGroup>
    </When>
    <Otherwise>
      <ItemGroup>
        <ProjectReference Include="..\ObservatoryCore\ObservatoryFramework\ObservatoryFramework.csproj" />
      </ItemGroup>
    </Otherwise>
  </Choose>
  

  <ItemGroup>
    <Compile Update="UI\PluginPanel.cs">
      <SubType>Component</SubType>
    </Compile>
  </ItemGroup>
  

  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="33.1.0" />
  </ItemGroup>

</Project>
